### ISSUE TITLE
Tracking: Support more examples

### ISSUE THREAD

**Issue by eryue0220** [eryue0220/unplugin-stylex#13]
This issue is used to track the frameworks or build tools need to support.

- [x] rollup https://github.com/eryue0220/unplugin-stylex/pull/27
- [x] webpack https://github.com/eryue0220/unplugin-stylex/pull/28
- [x] farm https://github.com/eryue0220/unplugin-stylex/pull/32
- [x] astro https://github.com/eryue0220/unplugin-stylex/pull/123
- [x] svelte https://github.com/eryue0220/unplugin-stylex/pull/47
- [x] solid https://github.com/eryue0220/unplugin-stylex/pull/46
